package application

import (
	"fmt"
	"strings"

	"milton_prism/core/services/migration/domain"
)

// stepProfile holds the stack-specific "how" for one action plan step kind.
type stepProfile struct {
	// Technique is the primary approach for this kind on this stack.
	technique string
	// Paths lists the file/directory patterns to create or reorganise.
	paths []string
	// Conventions describes naming and structural rules for this stack.
	conventions string
	// Example shows a concrete code sketch (≤6 lines, no real source).
	example string
}

// restructuringProfile provides stack-specific mechanics for every known
// action plan step kind. A nil profile means no profile exists for that stack.
type restructuringProfile struct {
	stackName string
	steps     map[string]stepProfile // keyed by ActionItem.Kind
}

// pythonFlaskProfile is the restructuring profile for Python / Flask codebases.
// Paths and conventions are coherent with the narratives generated by 2a (EnrichRoadmap).
var pythonFlaskProfile = &restructuringProfile{
	stackName: "Python / Flask",
	steps: map[string]stepProfile{
		"EXTRACT_DOMAIN": {
			technique:   "Create a `domain/` package at the project root. Move business logic (models, rules, entities) out of infrastructure modules into dedicated domain modules. Use constructor injection — domain classes must not import Flask, SQLAlchemy, or any I/O library directly.",
			paths:       []string{"domain/__init__.py", "domain/<entity_name>.py", "domain/state.py"},
			conventions: "One Python module per domain concept. snake_case filenames. No circular imports: domain/ must not import from the rest of the app.",
			example: `# domain/user.py  — domain model, no Flask/DB imports
class User:
    def __init__(self, user_id: int, email: str) -> None:
        self.user_id = user_id
        self.email = email`,
		},
		"DEFINE_BOUNDARIES": {
			technique:   "Group the extracted domain modules into service clusters. Create one sub-package per cluster under `services/`. Each cluster exposes a Flask Blueprint with a domain-aligned URL prefix. Cross-cluster calls are function calls for now; mark them with a `# FUTURE: inter-service` comment for extraction later.",
			paths:       []string{"services/<cluster_name>/__init__.py", "services/<cluster_name>/blueprint.py", "services/<cluster_name>/handlers.py"},
			conventions: "One Blueprint per service cluster. URL prefix matches the cluster name (e.g. `/users`, `/teams`). Blueprints are registered in the app factory, not in individual modules.",
			example: `# services/users/blueprint.py
from flask import Blueprint
users_bp = Blueprint("users", __name__, url_prefix="/users")`,
		},
		"DECOUPLE_STATE": {
			technique:   "Extract all module-level mutable state into a `StateManager` class in `domain/state.py`. Replace direct imports of the state module with constructor injection of `StateManager`. Instantiate it once in the Flask app factory and pass it as a dependency.",
			paths:       []string{"domain/state.py"},
			conventions: "No module-level mutable globals outside `StateManager`. All state access goes through getter/setter methods. `StateManager` is a plain Python class — no Flask dependency.",
			example: `# domain/state.py
class StateManager:
    def __init__(self) -> None:
        self._data: dict = {}
    def get(self, key: str):
        return self._data.get(key)
    def set(self, key: str, value) -> None:
        self._data[key] = value`,
		},
		"SPLIT_GOD_MODULE": {
			technique:   "Split the target module by responsibility. Group its functions into concern-named sibling modules (e.g. `auth.py`, `users.py`, `data.py`). Keep the original `__init__.py` as a thin re-exporter during the transition to avoid breaking existing imports. Remove the re-exports once all callers are updated.",
			paths:       []string{"<module_dir>/<concern>.py", "<module_dir>/__init__.py"},
			conventions: "Each sibling module has a single responsibility. Max ~150 LOC per module as a target. The transitional `__init__.py` re-export is a migration aid — remove it before the next iteration.",
			example: `# backend/__init__.py  — transitional re-export
from backend.auth import login, logout       # noqa: F401
from backend.users import get_user, list_users  # noqa: F401`,
		},
		"ADD_ROUTING": {
			technique:   "Create one Flask Blueprint file per service cluster under `routes/`. Each file registers only the HTTP routes belonging to that cluster and delegates to the corresponding service handler module. Register all blueprints in a central app factory.",
			paths:       []string{"routes/<cluster_name>.py", "app.py (or create_app factory)"},
			conventions: "One route file per service boundary. Route files contain no business logic — they call handler functions. `create_app()` iterates over blueprints and calls `app.register_blueprint()`.",
			example: `# routes/users.py
from flask import Blueprint
from services.users import handlers
users_routes = Blueprint("users_routes", __name__, url_prefix="/users")

@users_routes.get("/")
def list_users():
    return handlers.list_users()`,
		},
	},
}

// resolveProfile returns the restructuring profile for the given framework and
// technology list, or nil when no profile exists for that stack. Matching is
// case-insensitive; "flask" and "Flask" both match the Python/Flask profile.
func resolveProfile(framework string, technologies []string) *restructuringProfile {
	fw := strings.ToLower(strings.TrimSpace(framework))
	if fw == "flask" {
		return pythonFlaskProfile
	}
	// Secondary: technology list contains "Python" without a named framework
	// — still use the Python/Flask profile since that's the only Python profile.
	for _, t := range technologies {
		if strings.EqualFold(t, "flask") {
			return pythonFlaskProfile
		}
	}
	return nil
}

// BuildActionPlanPrompt assembles the deterministic Markdown export. No LLM
// is called. profile may be nil — in that case the export is the honest "no
// profile available" document.
func BuildActionPlanPrompt(
	repoURL string,
	migrationID uint64,
	roadmap *domain.RestructuringRoadmap,
	framework string,
	technologies []string,
	profile *restructuringProfile,
) []byte {
	var b strings.Builder

	stackLabel := "unknown"
	if profile != nil {
		stackLabel = profile.stackName
	} else if framework != "" {
		stackLabel = framework
	} else if len(technologies) > 0 {
		stackLabel = strings.Join(technologies, ", ")
	}

	// ── Header ────────────────────────────────────────────────────────────────
	b.WriteString(fmt.Sprintf("# Restructuring Action Plan — Migration #%d\n\n", migrationID))
	if repoURL != "" {
		b.WriteString(fmt.Sprintf("**Repository:** %s\n", repoURL))
	}
	b.WriteString(fmt.Sprintf("**Stack detected:** %s\n", stackLabel))
	b.WriteString("**Purpose:** Instructions for a code agent to assist the restructuring of this codebase into microservice-ready architecture.\n")

	// ── Honesty disclaimer ────────────────────────────────────────────────────
	b.WriteString(`
---

> **⚠ Important — read before executing any step**
>
> This plan is derived from static dependency analysis. The domain groupings and module
> classifications are **hypotheses** based on structural coupling data — they must be
> validated against the actual source code before executing any step.
>
> - Each step should be reviewed by a developer before the agent executes it.
> - The agent may misidentify module responsibilities; confirm by reading the files first.
> - Dependencies between steps are real: do not execute a step whose prerequisite is unresolved.
> - This document is **structured guidance for human-supervised, agent-assisted refactoring**,
>   not an autonomous script.

---

`)

	// ── No-profile hole ───────────────────────────────────────────────────────
	if profile == nil {
		b.WriteString(fmt.Sprintf("## Stack profile not available\n\n"))
		b.WriteString(fmt.Sprintf("The executable export for **%s** is not available yet.\n\n", stackLabel))
		b.WriteString("The action plan below describes **what** to do; the stack-specific **how** (file paths, conventions, code patterns) is not generated for this stack.\n\n")
		b.WriteString("Stack profiles are added incrementally. The full action plan is available in the restructuring report.\n\n")
		b.WriteString("---\n\n")
		b.WriteString("## Action Plan (stack-agnostic)\n\n")
		writeAgnosticPlan(&b, roadmap)
		writeAgentUsageSection(&b)
		return []byte(b.String())
	}

	// ── Full plan with profile ─────────────────────────────────────────────────
	b.WriteString("## Action Plan\n\n")
	for _, item := range roadmap.GetActionPlan() {
		writePlanStep(&b, item, profile)
	}

	writeAgentUsageSection(&b)
	return []byte(b.String())
}

func writePlanStep(b *strings.Builder, item *domain.ActionItem, profile *restructuringProfile) {
	blocking := ""
	if item.GetBlocking() {
		blocking = " · **BLOCKING**"
	}
	b.WriteString(fmt.Sprintf("### Step %d — %s (impact: +%d pts%s)\n\n",
		item.GetOrder(), item.GetKind(), item.GetImpact(), blocking))

	b.WriteString(fmt.Sprintf("**Subject:** %s\n\n", item.GetSubject()))
	b.WriteString(fmt.Sprintf("**What:** %s\n\n", item.GetAction()))

	if item.GetDependsOnStep() > 0 {
		b.WriteString(fmt.Sprintf("**Prerequisite:** Complete Step %d before starting this step.\n\n", item.GetDependsOnStep()))
	}

	sp, ok := profile.steps[item.GetKind()]
	if ok {
		b.WriteString("**How — " + profile.stackName + ":**\n\n")
		b.WriteString(sp.technique + "\n\n")
		if len(sp.paths) > 0 {
			b.WriteString("*Files / paths to create or reorganise:*\n")
			for _, p := range sp.paths {
				b.WriteString(fmt.Sprintf("- `%s`\n", p))
			}
			b.WriteString("\n")
		}
		if sp.conventions != "" {
			b.WriteString("*Conventions:* " + sp.conventions + "\n\n")
		}
		if sp.example != "" {
			b.WriteString("*Example sketch:*\n\n```python\n" + sp.example + "\n```\n\n")
		}
	}

	b.WriteString("---\n\n")
}

func writeAgnosticPlan(b *strings.Builder, roadmap *domain.RestructuringRoadmap) {
	for _, item := range roadmap.GetActionPlan() {
		blocking := ""
		if item.GetBlocking() {
			blocking = " · **BLOCKING**"
		}
		b.WriteString(fmt.Sprintf("### Step %d — %s (impact: +%d pts%s)\n\n",
			item.GetOrder(), item.GetKind(), item.GetImpact(), blocking))
		b.WriteString(fmt.Sprintf("**Subject:** %s\n\n", item.GetSubject()))
		b.WriteString(fmt.Sprintf("**What:** %s\n\n", item.GetAction()))
		if item.GetDependsOnStep() > 0 {
			b.WriteString(fmt.Sprintf("**Prerequisite:** Step %d\n\n", item.GetDependsOnStep()))
		}
		b.WriteString("---\n\n")
	}
}

func writeAgentUsageSection(b *strings.Builder) {
	b.WriteString(`## How to use this with your code agent

1. **Open your code agent** in the repository root.
2. **Paste this document** (or upload the .md file) as initial context.
3. **Work one step at a time.** Ask the agent to address Step 1 first. Review the diff before moving to Step 2.
4. **Validate before proceeding.** After each step, run your test suite and confirm no regressions before starting the next step.
5. **Override when needed.** The agent may suggest alternative approaches — prefer ones that maintain the structure described here (domain/ package, constructor injection, one blueprint per service).
6. **Blocking steps must be resolved in order.** Steps marked BLOCKING must be complete before any dependent step begins.
`)
}
