package assembler

import (
	"strings"
	"testing"
)

// buildProtoClosureFixture lays down a skeleton root that carries the canonical
// proto import-closure on disk (pagination → openapiv3/annotations → OpenAPIv3 +
// google/protobuf/descriptor) plus a platform buf.yaml with stale lint-ignore
// entries and a buf.lock — the real-world shape FRENTE 1 must resolve. Returns the
// root path.
func buildProtoClosureFixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()

	// Go scaffolding so the Go/Python profiles produce a real deliverable.
	writeFixture(t, root, "go.mod", "module milton_prism\n\nrequire (\n\tgithub.com/docker/docker v27.1.1+incompatible\n\tgithub.com/go-git/go-git/v5 v5.19.1\n\tgithub.com/go-enry/go-enry/v2 v2.9.6\n\tgithub.com/smacker/go-tree-sitter v0.0.0-20240827094217-dd81d9e9be82\n\tgithub.com/hibiken/asynq v0.26.0\n\tgithub.com/google/uuid v1.6.0\n)\n\nrequire (\n\tgithub.com/ProtonMail/go-crypto v1.1.6 // indirect\n\tgithub.com/redis/go-redis/v9 v9.14.1 // indirect\n\tgithub.com/moby/term v0.5.2 // indirect\n\tgithub.com/stretchr/objx v0.5.3 // indirect\n)\n")
	writeFixture(t, root, "go.sum", "h1:abc\n")
	writeFixture(t, root, "Makefile", "all:\n\techo go\n")
	writeFixture(t, root, "core/shared/auth_token/token.go", "package auth_token\n")
	// phpclassify must NOT ship (platform worker code).
	writeFixture(t, root, "core/shared/phpclassify/segment.go", "package phpclassify\n")
	writeFixture(t, root, "pkg/gateway/common/error/user_errors.go", "package error\n")

	// Platform buf.yaml with stale ignores + buf.lock.
	writeFixture(t, root, "protobuf/buf.yaml", `version: v2
modules:
  - path: proto
    lint:
      use:
        - STANDARD
      ignore:
        - proto/openapiv3
        - proto/openapi-spec.proto
deps:
  - buf.build/googleapis/googleapis
`)
	writeFixture(t, root, "protobuf/buf.go.gen.yaml", "version: v2\n")
	writeFixture(t, root, "protobuf/buf.lock", "# Generated by buf. DO NOT EDIT.\nversion: v2\ndeps:\n  - name: buf.build/googleapis/googleapis\n")

	// Canonical proto closure on disk (skeleton tree). The service proto itself is
	// supplied via ARTIFACTS (the agent writes it), so only the transitive deps live
	// here as skeleton sources.
	writeFixture(t, root, "protobuf/proto/milton_prism/types/pagination/v1/pagination.proto",
		"syntax=\"proto3\";\nimport \"openapiv3/annotations.proto\";\nimport \"google/api/field_behavior.proto\";\n")
	writeFixture(t, root, "protobuf/proto/milton_prism/types/query_params/v1/query_params.proto",
		"syntax=\"proto3\";\nimport \"openapiv3/annotations.proto\";\n")
	writeFixture(t, root, "protobuf/proto/openapiv3/annotations.proto",
		"syntax=\"proto3\";\nimport \"openapiv3/OpenAPIv3.proto\";\nimport \"google/protobuf/descriptor.proto\";\n")
	writeFixture(t, root, "protobuf/proto/openapiv3/OpenAPIv3.proto",
		"syntax=\"proto3\";\nimport \"google/protobuf/any.proto\";\n")
	// An over-vendored proto NO service imports — must be pruned.
	writeFixture(t, root, "protobuf/proto/google/protobuf/go_features.proto", "syntax=\"proto3\";\n")

	return root
}

// userServiceProtoArtifact is the generated service proto the agent ships under the
// canonical protobuf/proto tree; it imports pagination/query_params/openapiv3 and a
// couple of google WKTs (which resolve via buf deps, not on disk).
const userServiceProtoArtifact = `syntax = "proto3";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "milton_prism/types/pagination/v1/pagination.proto";
import "milton_prism/types/query_params/v1/query_params.proto";
import "openapiv3/annotations.proto";
`

// TestFrente1_GoProtoClosureAndBuf proves that a Go deliverable carrying the
// generated service proto pulls the FULL transitive import closure (pagination,
// query_params, openapiv3/annotations, openapiv3/OpenAPIv3) out of the skeleton,
// ships buf.lock, drops the over-vendored go_features.proto, and strips the stale
// buf.yaml ignore for proto/openapi-spec.proto while keeping the live proto/openapiv3
// ignore (openapiv3 now ships).
func TestFrente1_GoProtoClosureAndBuf(t *testing.T) {
	root := buildProtoClosureFixture(t)
	a := New(root, false, "go", "grpc", "")
	artifacts := []InputFile{
		{Path: "core/cmd/user-services/main.go", Content: "package main\n"},
		{Path: "protobuf/proto/milton_prism/services/user/v1/user_service.proto", Content: userServiceProtoArtifact},
		// An over-vendored proto the agent shipped that no service imports.
		{Path: "protobuf/proto/google/protobuf/go_features.proto", Content: "syntax=\"proto3\";\n"},
	}
	files, err := a.Assemble(artifacts)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	set := pathSet(files)

	// FRENTE 1: full closure present.
	for _, want := range []string{
		"protobuf/proto/milton_prism/services/user/v1/user_service.proto",
		"protobuf/proto/milton_prism/types/pagination/v1/pagination.proto",
		"protobuf/proto/milton_prism/types/query_params/v1/query_params.proto",
		"protobuf/proto/openapiv3/annotations.proto",
		"protobuf/proto/openapiv3/OpenAPIv3.proto",
		"protobuf/buf.lock",
	} {
		if !set[want] {
			t.Errorf("Go deliverable missing closure/buf file %q", want)
		}
	}
	// FRENTE 1: over-vendored proto pruned.
	if set["protobuf/proto/google/protobuf/go_features.proto"] {
		t.Errorf("Go deliverable shipped over-vendored go_features.proto (no service imports it)")
	}
	// FRENTE 1: stale buf.yaml ignore for the never-shipped openapi-spec.proto stripped;
	// the live openapiv3 ignore kept (openapiv3 ships).
	var buf string
	for _, f := range files {
		if f.Path == "protobuf/buf.yaml" {
			buf = string(f.Content)
		}
	}
	if strings.Contains(buf, "openapi-spec.proto") {
		t.Errorf("buf.yaml kept stale dangling ignore proto/openapi-spec.proto:\n%s", buf)
	}
	if !strings.Contains(buf, "proto/openapiv3") {
		t.Errorf("buf.yaml dropped the live proto/openapiv3 ignore (openapiv3 ships):\n%s", buf)
	}
	// FRENTE 2a: phpclassify never ships.
	if set["core/shared/phpclassify/segment.go"] {
		t.Errorf("Go deliverable leaked platform phpclassify code")
	}
}

// TestFrente1_PythonProtoClosure proves the Python deliverable also resolves the
// full proto import closure + ships buf.lock (previously only Rust/Node/Java did).
func TestFrente1_PythonProtoClosure(t *testing.T) {
	root := buildProtoClosureFixture(t)
	a := New(root, false, "python", "grpc", "")
	artifacts := []InputFile{
		{Path: "python/services/user/__main__.py", Content: "x = 1\n"},
		{Path: "protobuf/proto/milton_prism/services/user/v1/user_service.proto", Content: userServiceProtoArtifact},
	}
	files, err := a.Assemble(artifacts)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	set := pathSet(files)
	for _, want := range []string{
		"protobuf/proto/milton_prism/types/pagination/v1/pagination.proto",
		"protobuf/proto/openapiv3/annotations.proto",
		"protobuf/proto/openapiv3/OpenAPIv3.proto",
		"protobuf/buf.lock",
	} {
		if !set[want] {
			t.Errorf("Python deliverable missing closure/buf file %q", want)
		}
	}
}

// TestFrente2a_TidyGoMod proves the platform/agent-only direct + indirect requires
// are pruned from the assembled go.mod, while the deliverable's real deps survive.
func TestFrente2a_TidyGoMod(t *testing.T) {
	root := buildProtoClosureFixture(t)
	a := New(root, false, "go", "grpc", "")
	files, err := a.Assemble([]InputFile{{Path: "core/cmd/user-services/main.go", Content: "package main\n"}})
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	var gomod string
	for _, f := range files {
		if f.Path == "go.mod" {
			gomod = string(f.Content)
		}
	}
	if gomod == "" {
		t.Fatal("go.mod missing")
	}
	for _, dropped := range []string{
		"github.com/docker/docker",
		"github.com/go-git/go-git/v5",
		"github.com/go-enry/go-enry/v2",
		"github.com/smacker/go-tree-sitter",
		"github.com/hibiken/asynq",
		"github.com/ProtonMail/go-crypto",
		"github.com/redis/go-redis/v9",
		"github.com/moby/term",
	} {
		if strings.Contains(gomod, dropped) {
			t.Errorf("go.mod still declares pruned platform dep %q:\n%s", dropped, gomod)
		}
	}
	// Deliverable's real deps survive.
	for _, kept := range []string{"github.com/google/uuid", "github.com/stretchr/objx"} {
		if !strings.Contains(gomod, kept) {
			t.Errorf("go.mod wrongly dropped real dep %q:\n%s", kept, gomod)
		}
	}
}

// TestFrente2a_TidyGoModUnit drives tidyGoMod directly over a representative go.mod.
func TestFrente2a_TidyGoModUnit(t *testing.T) {
	merged := map[string][]byte{
		"go.mod": []byte("module milton_prism\n\ngo 1.25.0\n\nrequire (\n\tgithub.com/docker/docker v27.1.1+incompatible\n\tgithub.com/google/uuid v1.6.0\n)\n\nrequire (\n\tgithub.com/go-git/go-billy/v5 v5.9.0 // indirect\n\tgithub.com/spf13/cast v1.10.0 // indirect\n)\n"),
	}
	tidyGoMod(merged)
	out := string(merged["go.mod"])
	if strings.Contains(out, "github.com/docker/docker") {
		t.Errorf("docker not pruned:\n%s", out)
	}
	if strings.Contains(out, "go-git/go-billy") {
		t.Errorf("go-git indirect not pruned:\n%s", out)
	}
	if !strings.Contains(out, "github.com/google/uuid") || !strings.Contains(out, "github.com/spf13/cast") {
		t.Errorf("non-platform deps wrongly pruned:\n%s", out)
	}
	if !strings.Contains(out, "module milton_prism") || !strings.Contains(out, "go 1.25.0") {
		t.Errorf("module/go directives clobbered:\n%s", out)
	}
}

// TestFrente2a_PythonConfigPrune proves the Python pyproject mypy overrides + the
// .importlinter are rewritten to the generated service (no platform identity/
// repository/migration leakage), and fastapi/uvicorn are dropped for a gRPC cell.
func TestFrente2a_PythonConfigPrune(t *testing.T) {
	root := buildProtoClosureFixture(t)
	// Provide a realistic platform pyproject + importlinter in the skeleton.
	writeFixture(t, root, "python/__init__.py", "")
	writeFixture(t, root, "python/pyproject.toml", `[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.0"
uvicorn = "^0.34.0"
grpcio = "^1.68.0"
pydantic = "^2.10.0"

[[tool.mypy.overrides]]
module = [
    "services.identity.infrastructure.grpc_handlers.identity_handler",
    "services.identity.__main__",
    "shared.auth.extractor",
]
ignore_errors = true
`)
	writeFixture(t, root, "python/.importlinter", `[importlinter]
root_packages =
    shared
    services
include_external_packages = True

[importlinter:contract:identity-domain-independence]
name = Identity domain may not import ports, application, or infrastructure
type = forbidden
source_modules =
    services.identity.domain
forbidden_modules =
    services.identity.infrastructure
    grpc
`)
	a := New(root, false, "python", "grpc", "")
	artifacts := []InputFile{
		{Path: "python/services/user/__main__.py", Content: "x = 1\n"},
		{Path: "python/services/user/domain/user.py", Content: "class User: ...\n"},
	}
	files, err := a.Assemble(artifacts)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	var pyproject, linter string
	for _, f := range files {
		switch f.Path {
		case "core/pyproject.toml":
			pyproject = string(f.Content)
		case "core/.importlinter":
			linter = string(f.Content)
		}
	}
	if pyproject == "" || linter == "" {
		t.Fatalf("pyproject/.importlinter missing (pyproject present=%v linter present=%v)", pyproject != "", linter != "")
	}
	// mypy overrides: platform service gone, generated service present, non-service kept.
	if strings.Contains(pyproject, "services.identity.") {
		t.Errorf("pyproject still references platform service services.identity.*:\n%s", pyproject)
	}
	if !strings.Contains(pyproject, "services.user.") {
		t.Errorf("pyproject did not remap mypy override to generated service services.user.*:\n%s", pyproject)
	}
	if !strings.Contains(pyproject, "shared.auth.extractor") {
		t.Errorf("pyproject dropped the non-service override shared.auth.extractor:\n%s", pyproject)
	}
	// fastapi/uvicorn dropped for gRPC.
	for _, dep := range []string{"fastapi", "uvicorn"} {
		if strings.Contains(pyproject, dep+" = \"") {
			t.Errorf("gRPC Python deliverable kept unused dep %q:\n%s", dep, pyproject)
		}
	}
	// .importlinter rewritten to the generated service.
	if strings.Contains(linter, "services.identity.") {
		t.Errorf(".importlinter still references platform service identity:\n%s", linter)
	}
	if !strings.Contains(linter, "services.user.domain") {
		t.Errorf(".importlinter not regenerated for generated service user:\n%s", linter)
	}
}

// TestFrente3_StoreSpecificEnvDefaults proves the SQL .env.example DB defaults match
// the cell's engine: MySQL/MariaDB → port 3306 + mysql URL; Postgres → 5432.
func TestFrente3_StoreSpecificEnvDefaults(t *testing.T) {
	cases := []struct {
		profile, store, root, wantPort, wantScheme, badPort string
	}{
		{"rust", "mysql", "rust", "DB_PORT=3306", "mysql://", "DB_PORT=5432"},
		{"rust", "postgres", "rust", "DB_PORT=5432", "postgres://", "DB_PORT=3306"},
		{"go", "mysql", "core", "DB_PORT=3306", "tcp(", "DB_PORT=5432"},
		{"python", "mysql", "python", "DB_PORT=3306", "aiomysql", "DB_PORT=5432"},
		{"node", "mysql", "node", "DB_PORT=3306", "mysql://", "DB_PORT=5432"},
	}
	for _, tc := range cases {
		t.Run(tc.profile+"_"+tc.store, func(t *testing.T) {
			root := buildSkeletonFixture(t)
			a := New(root, false, tc.profile, "grpc", tc.store)
			var artPath string
			switch tc.profile {
			case "go":
				artPath = "core/cmd/user-services/main.go"
			default:
				artPath = tc.root + "/services/user/main.txt"
			}
			files, err := a.Assemble([]InputFile{{Path: artPath, Content: "x\n"}})
			if err != nil {
				t.Fatalf("Assemble: %v", err)
			}
			var env string
			for _, f := range files {
				if strings.HasSuffix(f.Path, "user/.env.example") || strings.HasSuffix(f.Path, "user-services/.env.example") {
					env = string(f.Content)
				}
			}
			if env == "" {
				t.Fatalf("no .env.example produced")
			}
			if !strings.Contains(env, tc.wantPort) {
				t.Errorf("%s+%s .env.example missing %q; got:\n%s", tc.profile, tc.store, tc.wantPort, env)
			}
			if strings.Contains(env, tc.badPort) {
				t.Errorf("%s+%s .env.example has wrong-engine %q; got:\n%s", tc.profile, tc.store, tc.badPort, env)
			}
			if !strings.Contains(env, tc.wantScheme) {
				t.Errorf("%s+%s .env.example missing %q DSN scheme; got:\n%s", tc.profile, tc.store, tc.wantScheme, env)
			}
		})
	}
}

// TestAssemble_JavaGRPC_RelocatesVendoredProtos proves the Java guardrail: the
// agent's vendored well-known / google.api protos (written under
// java/services/<svc>/src/main/proto-include/google/…) are relocated to the
// canonical protobuf/proto/google/… tree, NO .proto survives under core/, and the
// per-service pom.xml is rewritten to drop the proto-include
// <additionalProtoPathElement> and repoint <protoSourceRoot> at the canonical
// ../../../protobuf/proto path. It is the Java homologue of
// TestAssemble_RustGRPC_RelocatesVendoredProtos.
func TestAssemble_JavaGRPC_RelocatesVendoredProtos(t *testing.T) {
	root := buildSkeletonFixture(t)

	a := New(root, true, "java", "grpc", "")

	pom := `<project>
  <artifactId>user</artifactId>
  <build>
    <plugins>
      <plugin>
        <artifactId>protobuf-maven-plugin</artifactId>
        <configuration>
          <protoSourceRoot>${project.basedir}/src/main/proto</protoSourceRoot>
          <additionalProtoPathElement>${project.basedir}/src/main/proto-include</additionalProtoPathElement>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
`
	artifacts := []InputFile{
		{Path: "java/services/user/pom.xml", Content: pom},
		{Path: "java/services/user/src/main/java/com/example/user/UserApplication.java", Content: "package com.example.user;\n"},
		// Vendored third-party protos under the proto-include dir.
		{Path: "java/services/user/src/main/proto-include/google/api/annotations.proto", Content: "syntax = \"proto3\";\npackage google.api;\n"},
		{Path: "java/services/user/src/main/proto-include/google/api/http.proto", Content: "syntax = \"proto3\";\npackage google.api;\n"},
		{Path: "java/services/user/src/main/proto-include/google/api/field_behavior.proto", Content: "syntax = \"proto3\";\npackage google.api;\n"},
		// A second service vendoring the SAME proto — must dedup, not collide.
		{Path: "java/services/order/src/main/proto-include/google/api/annotations.proto", Content: "syntax = \"proto3\";\npackage google.api;\n"},
		{Path: "java/services/order/pom.xml", Content: pom},
	}
	files, err := a.Assemble(artifacts)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	set := pathSet(files)

	// Invariant: zero .proto under core/ and no proto-include dir survives.
	for _, f := range files {
		if strings.HasPrefix(f.Path, "core/") && strings.HasSuffix(f.Path, ".proto") {
			t.Errorf("proto leaked under core/: %q", f.Path)
		}
		if strings.Contains(f.Path, "/proto-include/") {
			t.Errorf("proto-include dir survived: %q", f.Path)
		}
	}

	// Relocated to the canonical protobuf/proto/ tree (untouched by java/→core/).
	for _, want := range []string{
		"protobuf/proto/google/api/annotations.proto",
		"protobuf/proto/google/api/http.proto",
		"protobuf/proto/google/api/field_behavior.proto",
	} {
		if !set[want] {
			t.Errorf("vendored proto not relocated to canonical path: %q missing", want)
		}
	}

	// pom.xml rewritten: no proto-include additionalProtoPathElement; protoSourceRoot
	// repointed at the canonical tree.
	var gotPom string
	for _, f := range files {
		if f.Path == "core/services/user/pom.xml" {
			gotPom = string(f.Content)
		}
	}
	if gotPom == "" {
		t.Fatal("core/services/user/pom.xml missing")
	}
	if strings.Contains(gotPom, "proto-include") {
		t.Errorf("pom.xml still references proto-include:\n%s", gotPom)
	}
	if strings.Contains(gotPom, "additionalProtoPathElement") {
		t.Errorf("pom.xml still carries an additionalProtoPathElement:\n%s", gotPom)
	}
	if !strings.Contains(gotPom, "<protoSourceRoot>../../../protobuf/proto</protoSourceRoot>") {
		t.Errorf("pom.xml protoSourceRoot not repointed at canonical ../../../protobuf/proto:\n%s", gotPom)
	}
}

// TestAudit_NoProtoUnderCore_AllProfiles is the lock-in for TASK A: after assembly,
// NO `.proto` file may live anywhere under core/ for ANY of the five language
// profiles. Each profile is fed a generated service proto under the canonical
// protobuf/proto tree PLUS a stray/vendored .proto under its source tree (which the
// rename would otherwise carry to core/); the assembler must keep every .proto under
// protobuf/proto/ only.
func TestAudit_NoProtoUnderCore_AllProfiles(t *testing.T) {
	cases := []struct {
		profile string
		// vendored is a .proto the agent wrote under the profile's source tree (the
		// thing that, left in place, would land under core/ after the rename).
		vendored InputFile
		// extra source artifact so the profile produces a real deliverable.
		src InputFile
	}{
		{
			profile:  "go",
			vendored: InputFile{Path: "core/services/user/proto/user.proto", Content: "syntax=\"proto3\";\n"},
			src:      InputFile{Path: "core/cmd/user-services/main.go", Content: "package main\n"},
		},
		{
			profile:  "python",
			vendored: InputFile{Path: "python/services/user/proto/user.proto", Content: "syntax=\"proto3\";\n"},
			src:      InputFile{Path: "python/services/user/__main__.py", Content: "x = 1\n"},
		},
		{
			profile:  "node",
			vendored: InputFile{Path: "node/services/user/proto/user.proto", Content: "syntax=\"proto3\";\n"},
			src:      InputFile{Path: "node/services/user/src/main.ts", Content: "export {}\n"},
		},
		{
			profile:  "rust",
			vendored: InputFile{Path: "rust/services/user/proto_include/google/api/annotations.proto", Content: "syntax=\"proto3\";\n"},
			src:      InputFile{Path: "rust/services/user/src/main.rs", Content: "fn main() {}\n"},
		},
		{
			profile:  "java",
			vendored: InputFile{Path: "java/services/user/src/main/proto-include/google/api/annotations.proto", Content: "syntax=\"proto3\";\n"},
			src:      InputFile{Path: "java/services/user/src/main/java/com/example/user/UserApplication.java", Content: "package com.example.user;\n"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.profile, func(t *testing.T) {
			root := buildSkeletonFixture(t)
			a := New(root, true, tc.profile, "grpc", "")
			files, err := a.Assemble([]InputFile{
				tc.src,
				tc.vendored,
				// A legitimately-placed generated service proto under the canonical tree.
				{Path: "protobuf/proto/user/v1/user.proto", Content: "syntax=\"proto3\";\n"},
			})
			if err != nil {
				t.Fatalf("Assemble: %v", err)
			}
			for _, f := range files {
				if strings.HasPrefix(f.Path, "core/") && strings.HasSuffix(f.Path, ".proto") {
					t.Errorf("[%s] .proto leaked under core/: %q", tc.profile, f.Path)
				}
			}
			// Sanity: the canonical proto still ships (assembler kept the proto tree).
			if !pathSet(files)["protobuf/proto/user/v1/user.proto"] {
				t.Errorf("[%s] canonical service proto dropped from protobuf/proto/", tc.profile)
			}
		})
	}
}

// TestFrente3_NoAuthOmitsJWTBlock proves a service whose generated code never reads
// an auth secret gets NO JWT block in its .env.example (only the cell's DB +
// protocol vars), while a service that reads JWT_SECRET keeps it.
func TestFrente3_NoAuthOmitsJWTBlock(t *testing.T) {
	root := buildSkeletonFixture(t)
	a := New(root, false, "rust", "grpc", "")
	files, err := a.Assemble([]InputFile{
		// noauth: no JWT/token reference anywhere in the service.
		{Path: "rust/services/noauth/src/main.rs", Content: "fn main() { println!(\"hi\"); }\n"},
		// withauth: reads JWT_SECRET.
		{Path: "rust/services/withauth/src/main.rs", Content: "fn main() { let _ = std::env::var(\"JWT_SECRET\"); }\n"},
	})
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	var noauthEnv, withauthEnv string
	for _, f := range files {
		switch f.Path {
		case "core/services/noauth/.env.example":
			noauthEnv = string(f.Content)
		case "core/services/withauth/.env.example":
			withauthEnv = string(f.Content)
		}
	}
	if noauthEnv == "" || withauthEnv == "" {
		t.Fatalf("env examples missing (noauth present=%v withauth present=%v)", noauthEnv != "", withauthEnv != "")
	}
	if strings.Contains(noauthEnv, "JWT_SECRET") {
		t.Errorf("no-auth service .env.example wrongly advertises JWT_SECRET:\n%s", noauthEnv)
	}
	if !strings.Contains(withauthEnv, "JWT_SECRET") {
		t.Errorf("auth service .env.example missing JWT_SECRET:\n%s", withauthEnv)
	}
}
